version: '3.7'
services:
  develop:
    image: ${AUTHOR}/${PROJECT}:develop
    container_name: ${PROJECT}-develop
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "${PORT_DEVELOP}:4200"
      - "49153:49153"
      - "9876:9876"
      - "49152:49152"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules:delegated
    entrypoint: /docker-entrypoint.sh
  prod:
    image: ${AUTHOR}/${PROJECT}:prod
    container_name: ${PROJECT}-prod
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - "${PORT_PROD}:80"
    command: nginx -g 'daemon off;'
