version: '3.7'
services:
  develop:
    image: ${AUTHOR}/${PROJECT_NAME}:develop
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "4200:4200"
      - "49153:49153"
      - "9876:9876"
      - "49152:49152"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules:delegated
    entrypoint: /docker-entrypoint.sh
